server:
  port: 8888
spring:
    profiles:
      active: native
    cloud:
      config:
        server:
          native:
            searchLocations: file:////home/guitimoteo/Documents/workspace/sts/spmia-chapter2/confsrv/src/main/resources/config/licensingserver